spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Root@123
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
server.port: 8081
